== Prerequisites

==== 1. Delete Temp directory

    rm -rf ~/hyla/MyBlankProject/
    rm -rf ~/hyla/MyBookProject
    rm -rf ~/hyla/MyPdfProject/
    rm -rf ~/hyla/MyTocProject/
    rm -rf ~/hyla/MyTrainingProject/
    rm -rf ~/hyla/MyTrainingExercisesProject/
    rm -rf ~/hyla/MyDeckSlideShow/
    rm -rf ~/hyla/MyRevealSlideShow/

==== 2. Install Gem Hyla 1.0.x

    gem install hyla -v 1.0.x

== 1. Blank Project & Artefacts

Using hyla we will create a new project (= directory) and add artefacts (article, audio, video, image, source, table)

== 1. Create a Blank Project (with or without --force option)

    hyla new --blank ~/hyla/MyBlankProject
    hyla new --blank ~/hyla/MyBlankProject --force

== 2. Create a Blank Project without _config.yaml config file, add artefact

    cd ~/hyla
    rm -rf MyBlankProject/
    hyla new --blank MyBlankProject --force
    hyla create --t asciidoc --a article --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a book --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a image --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a audio --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a video --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a source --d ~/hyla/MyBlankProject
    hyla create --t asciidoc --a table --d ~/hyla/MyBlankProject

== 3.  Create a Blank Project using _config.yaml config file, add artefacts

    cd ~/hyla
    rm -rf MyBlankProject/
    hyla new --blank MyBlankProject --force
    cd MyBlankProject
    hyla create --a article
    hyla create --a book
    hyla create --a image
    hyla create --a audio
    hyla create --a video
    hyla create --a source
    hyla create --a table

=== 4. Generate HTML Content of an existing project (asciidoc 2 html)

    hyla generate --r adoc2html --s ~/hyla/MyBlankProject/ --d ~/hyla/MyBlankProject/generated_content

=== 5. Generate HTML Content of an existing project (asciidoc 2 html) with a different style

    Styles available : redhat, asciidoctor, colony, foundation, foundation-lime, foundation-potion, github, golo, iconic, maker, readthedocs, riak, rocket-panda, rubygems

    hyla generate --r adoc2html --s ~/hyla/MyBlankProject/ --d ~/hyla/MyBlankProject/generated_content --style redhat
    hyla generate --r adoc2html --s ~/hyla/MyBlankProject/ --d ~/hyla/MyBlankProject/generated_content --style github
    hyla generate --r adoc2html --s ~/hyla/MyBlankProject/ --d ~/hyla/MyBlankProject/generated_content --style foundation

=== 6. Generate HTML Content within project

    hyla generate --r adoc2html --s . --d generated_content

=== 7. Generate HTML Content within project & using Config File

   As destination directory is not longer '.' (which is the case when we add artefacts using `hyla create` command, then we must change the destination directory to `generated_content`. the original file is
   still available as it will backup by ruby

    ruby -i.bak -pe 'sub(%r{destination: .},"destination: generated_content")' _config.yml
    hyla generate
    hyla generate --style foundation


== 2. Project from Template

=== 1. Create a project using a template (training)

    cd ~/hyla
    hyla new --t training MyTrainingProject

    // TODO Refactor Training Exercises Template
    hyla new --t training-exercises MyTrainingExercisesProject

    // TODO - Add images
    hyla new --t book MyBookProject

=== 2. Generate content and watch it

    cd ~/hyla/MyTrainingProject
    ruby -i.bak -pe 'sub(%r{destination: .},"destination: generated_content")' _config.yml
    hyla generate

    hyla watch --s ~/hyla/MyTrainingProject/ --d ~/hyla/MyTrainingProject/generated_content

== 3. Table Of Content To asciidoc

=== 1. Generate an asciidoctor project from a Table of Content

    cd ~/hyla
    rm -rf MyBlankProject/
    hyla generate --r toc2adoc --p my-project --d ~/hyla/MyTocProject/ --toc ~/MyProjects/hyla/data/toc.adoc
    hyla generate --r adoc2html --s ~/hyla/MyTocProject/ --d ~/hyla/MyTocProject/generated_content

    hyla watch --s ~/hyla/MyTocProject/ --d ~/hyla/MyTocProject/generated_content

=== 2. Generate an asciidoctor project from a Table of Content using YAML config file and watch content

    rm -rf ~/hyla/MyTocProject
    cd ~/hyla
    hyla new --blank MyTocProject
    cd MyTocProject
    hyla generate --r toc2adoc

    # Change destination in config files or pass info as option
    # cd ../MyTocProject/
    # subl _config.yml
    hyla generate --r adoc2html

    hyla watch --s ~/hyla/MyTocProject/ --d generated_content

=== 3. Generate a DeckJS Slideshow for a module

    cd ~/hyla/MyTocProject
    hyla generate --backend deckjs --s  A_Introduction_module/ --d A_Introduction_module/generated_content --r index2slide

=== 4. Generate a DeckJS Slideshow for a Project (all the TOC)

    cd ~/hyla/MyTocProject
    hyla generate --backend deckjs --s  . --d generated_content --r index2slide --trace

== 5. Server content locally - HTTP Server

    hyla serve -P 4000 -H localhost -b /hyla/ --out_dir ~/hyla/MyTrainingProject/generated_content/

== 6. Generate a Slideshow

=== 1. DeckJS

    rm -rf  ~/hyla/MyDeckSlideShow
    cd ~/hyla
    hyla new --blank MyDeckSlideShow
    hyla create --t slideshow --a deckjs --d MyDeckSlideShow
    hyla generate --backend deckjs --s  ~/hyla/MyDeckSlideShow --d ~/hyla/MyDeckSlideShow/generated_content --r adoc2slide

=== 2. Different DeckJS Style options

    hyla generate --backend deckjs --s  ~/hyla/MyDeckSlideShow --d ~/hyla/MyDeckSlideShow/generated_content --r index2slide --a deckjs_theme=swiss,deckjs_transition=fade
    hyla generate --backend deckjs --s  ~/hyla/MyDeckSlideShow --d ~/hyla/MyDeckSlideShow/generated_content --r index2slide --a deckjs_theme=web-2.0,deckjs_transition=horizontal-slide

===  3. RevealJS

    rm -rf ~/hyla/MyRevealSlideShow
    cd ~/hyla
    hyla new --blank MyRevealSlideShow
    hyla create --t slideshow --a revealjs --d MyRevealSlideShow
    cd MyRevealSlideShow
    hyla generate --backend revealjs --s . --d generated_content --r adoc2slide

    open http://localhost:4000/hyla/slideshow_revealjs.html &

    hyla serve -P 4000 -H localhost -b /hyla/ --out_dir ~/hyla/MyRevealSlideShow/generated_content/

== 7. Generate a PDF

A PDF document can be created using the rendering option `html2pdf`. To render the HTML file, Hyla uses the following Ruby
libraries https://github.com/pdfkit/pdfkit[pdfkit] and https://github.com/wkhtmltopdf/wkhtmltopdf[wkhtmltopdf].

    cd ~/hyla
    rm -rf MyPdfroject/
    hyla new --blank MyPdfProject --force
    cd MyPdfProject
    hyla create --a book
    hyla create --a image

    # Change destination firm local '.' to 'generated_content'
    ruby -i.bak -pe 'sub(%r{destination: .},"destination: generated_content")' _config.yml

    # Generate HTML content using foundation stylesheet
    hyla generate --style foundation

    # We change the rendering from adoc2html to html2pdf
    ruby -i.bak -pe 'sub(%r{rendering: adoc2html},"rendering: html2pdf")' _config.yml

    # Source directory & Destination directory
    ruby -i.bak -pe 'sub(%r{source: .},"source: ./generated_content")' _config.yml
    ruby -i.bak -pe 'sub(%r{destination: generated_content},"destination: ./generated_content/pdf")' _config.yml

    # We will generate the PDF file for the image and book
    hyla generate -f asciidoc_book.html
    hyla generate -f asciidoc_image.html

    # Result can be opened and viewed
    open generated_content/pdf/asciidoc_book.pdf
    open generated_content/pdf/asciidoc_image.pdf





