module Hyla
  module Commands
    class Sendmail < Command

      # SENDER        = 'Charles Moulliard <ch007m@gmail.com>'
      SENDER = 'Charles Moulliard <cmoulliard@redhat.com>'
      RECIPIENTS = 'cmoulliard@redhat.com'
      # RECIPIENTS = 'cmoulliard@redhat.com'
      # RECIPIENTS    = 'ch007m@gmail.com'
      # RECIPIENTS  = 'bomoran7@gmail.com'

      ROOT_DIR = '/Users/chmoulli/RedHat/GPE/Admin/Status-Report/2014/generated_content/'
      FILE_NAME = "chm-status-weeks-2001-2401.html"

      SUBJECT = 'Weekly Report\'s Charles - 20 to 24 January 2014'
      BODY_MSG = <<-EOS
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>REPORT</title>
        <link type="text/css" rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/5.0.3/css/foundation.min.css" />
        <link type="text/css" rel="stylesheet" href="http://cdn.jsdelivr.net/normalize/2.1.3/normalize.min.css" />
    </head>
    <body>
     <div class="row">
        <!-- Main Content -->
        <div class="large-9 columns" role="content">
          <article>
            <h4>#{SUBJECT}</h4>
            <p>Attached as <a href=\'#{FILE_NAME}'>HTML file to this email</a></p>
            <p>Generated by Hyla Tool</p>
            </p>
            <p>Remark : html Link works with Thunderbird, Gmail clients but not using Zimbra Web Client</p>
          </article>
        </div>
    </div>
    </body>
    </html>
      EOS

      FILE_LOCATION = [ROOT_DIR, FILE_NAME] * '/'

      def self.process(args, options)

        mail = Mail.new do
          to RECIPIENTS
          from SENDER
          subject SUBJECT
          content_type 'multipart/related'
        end

        attachment = File.read(FILE_LOCATION)
        mail.attachments[FILE_NAME] = {
            :mime_type => 'application/x-html',
            :content => attachment}

        inline_html = inline_body_with_attachments(BODY_MSG, mail.attachments)

        html_part = Mail::Part.new do
          content_type 'text/html; charset=UTF-8'
          body inline_html
        end

        print "Inline HTML : " + inline_html

        mail.html_part = html_part

        mail.delivery_method :smtp,
                             :address => 'smtp.corp.redhat.com',
                             :domain => 'chm-macbook-pro.local',
                             :port => 25,
                             :enable_starttls => true,
                             :openssl_verify_mode => 'none'

=begin
      mail.delivery_method :smtp,
                           :address              => 'smtp.gmail.com',
                           :domain               => 'chm-macbook-pro.local',
                           :port                 => 587,
                           :user_name            => 'ch007m',
                           :password             => 'b1kers99!',
                           :authentication       => 'PLAIN',
                           :enable_starttls      => true,
                           :openssl_verify_mode  => 'none'
=end

        mail.deliver!
        print "Email send to server from #{SENDER} corresponding to #{SUBJECT}"
      end

      def self.inline_body_with_attachments(html, attachments)
        attachments.each do |attachment|
          if (html =~ /#{attachment.filename}/)
            html = html.sub(attachment.filename, "cid:#{attachment.cid}")
          end
        end
        return html
      end

    end # class
  end # module Commands
end # module Hyla