:homepage: http://github.com/cmoulliard/hyla
:docs: https://github.com/cmoulliard/hyla/blob/master/documentation/introduction.adoc
:sources: https://github.com/cmoulliard/hyla
:issues: https://github.com/cmoulliard/hyla/issues/

== Install using the gem

The latest source code is located in the {sources}[Hyla git repository] on GitHub. Hyla can be installed via the +gem+ command, bundler.

Use `gem install` command to deploy Hyla :

    $ gem install hyla -y

NOTE :  The option `-y` will tell to rubyGems to deploy the gem but also the dependencies required

An alternative is to create a Gemfile and add this line :

    gem 'hyla'

And then execute:

    $ bundle

**Or** install it yourself as:

    $ gem install hyla -v 1.0.7.pre.x

== Build the project

In order to build the Hyla project, we recommend that you clone the project locally (or to fork the project), next you move to the project cloned
and finally, run the following command :
    
    rake build

This command will create a gem of the project

== To publish the Hyla Gem to your machine

    rake install

== To push to the gems ruby HTTP Server

    rake deploy

== To delete a release pushed to RubyGems (= yank)

    gem yank hyla -v 1.0.x

== To create a release, generate a tagged release and publish it to Gem Repo

    rake install
    git commit -m "Release Hyla 1.0.7.pre.x" -a
    git push
    git tag -a hyla-1.0.7.pre.x -m "Release hyla 1.0.7.pre.x"
    git push origin hyla-1.0.7.pre.x

    rake deploy
