:homepage: http://github.com/cmoulliard/hyla
:docs: https://github.com/cmoulliard/hyla/blob/master/documentation/introduction.adoc
:sources: https://github.com/cmoulliard/hyla
:issues: https://github.com/cmoulliard/hyla/issues/

== Install the gem

Use `gem install` command to deploy Hyla :

    $ gem install hyla -y

NOTE :  The option `-y` will tell to rubyGems to deploy the gem but also the dependencies required

== Build the project from the code 

* Generate the gem

In order to build the Hyla project, we recommend that you clone the project locally (or fork it) {sources}[from the Hyla git repository], next you move to the project cloned
and finally, run the following command :
    
    rake build

This command will create a gem of the project

* To install theGem to your machine, run this command

    rake install
    
* If you would like to change the scss files, styles and regenerate the css, use this command
    
    rake compass

* To publish the gem to the RubyGems Web Server, use this command

    rake deploy

* To create a release, generate a tagged release and publish it to Gem Repo

    rake install
    git commit -m "Release Hyla 1.0.7.pre.x" -a
    git push
    git tag -a hyla-1.0.7.pre.x -m "Release hyla 1.0.7.pre.x"
    git push origin hyla-1.0.7.pre.x

    rake deploy
    
* To delete a release pushed to RubyGems (= yank)

    gem yank hyla -v 1.0.x
